language: node_js

install:
  - npm install
  
node_js:
  - 0.10
  
services: 
  - mongodb
  
script:
  - gulp build 
  
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"